# KEDA, so counter-api scales on the request rate it actually serves rather
# than on CPU alone.
#
# This does not remove the HorizontalPodAutoscaler. A ScaledObject *creates*
# one -- named keda-hpa-<scaledobject> -- and KEDA registers itself as the
# external metrics API server that feeds it. What changes is the input: a
# PromQL query against VMSingle instead of metrics-server's CPU readings.
# counter-api uses ~0.1 core per pod at 5000 rps against a 100m request, so
# CPU sits near 100% of request across most of the useful range and makes a
# poor scaling signal; counter_api_http_requests_total is the direct one.
#
# The ScaledObject itself lives in the application chart
# (deploy/helm/counter-api/templates/scaledobject.yaml) so Argo CD owns it
# next to the Deployment it scales. Terraform only installs the controller.

resource "kubectl_manifest" "keda" {
  count = var.enable_keda ? 1 : 0

  yaml_body = yamlencode({
    apiVersion = "argoproj.io/v1alpha1"
    kind       = "Application"
    metadata = {
      name      = "keda"
      namespace = var.argocd_namespace
      # Without this a delete removes only the Application CR and leaves the
      # CRDs, the webhooks and the namespace behind -- and a stale
      # ValidatingWebhookConfiguration pointing at a Service that no longer
      # exists rejects every ScaledObject write afterwards.
      finalizers = ["resources-finalizer.argocd.argoproj.io"]
    }
    spec = {
      project = "default"
      destination = {
        server    = "https://kubernetes.default.svc"
        namespace = var.keda_namespace
      }
      source = {
        repoURL        = "https://kedacore.github.io/charts"
        chart          = "keda"
        targetRevision = var.keda_chart_version
        helm = {
          valuesObject = local.keda_values
        }
      }
      syncPolicy = {
        automated = {
          prune    = true
          selfHeal = true
        }
        syncOptions = [
          # KEDA has no pods on the system nodes to schedule around, no PVCs
          # and no LoadBalancer, so the namespace needs none of the teardown
          # ordering that monitoring_namespace does -- Argo CD can own it.
          "CreateNamespace=true",
          # The ScaledJob CRD alone is past the 262 KiB
          # last-applied-configuration annotation limit of client-side apply.
          "ServerSideApply=true",
          "RespectIgnoreDifferences=true",
        ]
      }
      # certificates.autoGenerated has the operator mint the webhook's serving
      # cert at runtime and patch the caBundle into these objects. The chart
      # renders them with an empty caBundle, so Argo CD sees the patched value
      # as drift and selfHeal would wipe it on every sync -- breaking the
      # webhook until the operator noticed and patched it back.
      ignoreDifferences = [
        {
          group = "admissionregistration.k8s.io"
          kind  = "ValidatingWebhookConfiguration"
          name  = "keda-admission"
          # keda-admission carries six webhook entries (vscaledobject,
          # vscaledjob, vtriggerauthentication...), each with its own
          # caBundle, so this cannot be a fixed /webhooks/0 pointer.
          jqPathExpressions = [".webhooks[].clientConfig.caBundle"]
        },
        {
          group        = "apiregistration.k8s.io"
          kind         = "APIService"
          name         = "v1beta1.external.metrics.k8s.io"
          jsonPointers = ["/spec/caBundle"]
        },
      ]
    }
  })

  depends_on = [module.eks, time_sleep.wait_for_argocd_crds]
}

# 05-app-deployment.tf's Application waits on this.
#
# The resource above only creates an `Application` object; Terraform returns
# the moment the CR exists. Argo CD still has to pull the chart, sync it, and
# have the API server register keda.sh/v1alpha1 before a ScaledObject is a
# valid kind. The chart guards its ScaledObject on that API being present
# (same pattern as the VMServiceScrape), so an earlier sync of the application
# renders no autoscaler at all -- and with autoscaling.keda.enabled the plain
# CPU HPA is not rendered either. The Deployment would sit at replicaCount
# until Argo CD's next reconcile.
resource "time_sleep" "wait_for_keda_crds" {
  count = var.enable_keda ? 1 : 0

  depends_on      = [kubectl_manifest.keda]
  create_duration = var.keda_sync_wait
}
